# Generated by Django 3.2.15 on 2022-09-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_booking_service_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
