# Generated by Django 3.2.15 on 2022-09-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_auto_20220903_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
