# Generated by Django 3.2.15 on 2022-09-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='name',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='isBusy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time_slot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
