# Generated by Django 3.2.15 on 2022-09-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_auto_20220903_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garage',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
