# Generated by Django 3.2.15 on 2022-09-04 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0007_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_date', models.CharField(blank=True, max_length=20, null=True)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='working_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='garage.workingdate'),
        ),
    ]
