# Generated by Django 3.2.15 on 2022-09-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0009_auto_20220904_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='working_date',
        ),
        migrations.DeleteModel(
            name='WorkingDate',
        ),
    ]
