# Generated by Django 3.2.15 on 2022-09-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0010_auto_20220904_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name_plural': 'Lịch hẹn'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Dịch Vụ'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name_plural': 'Thời gian làm việc'},
        ),
        migrations.AddField(
            model_name='booking',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
