# Generated by Django 3.2.15 on 2022-09-08 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garage', '0011_auto_20220907_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garage',
            options={'verbose_name_plural': 'Thông Tin Cửa Hàng'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(null=True, verbose_name='Ngày đặt'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='isCompleted',
            field=models.BooleanField(default=False, verbose_name='Đã xử lí'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số ĐT'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.service', verbose_name='Dịch vụ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.timeslot', verbose_name='Khung giờ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Giới thiệu cửa hàng'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tên cửa hàng'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tên Dịch Vụ'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(blank=True, max_length=255, verbose_name='Giá (VND)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='time_todo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Thời gian (phút)'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='isBusy',
            field=models.BooleanField(default=False, verbose_name='Nghỉ'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time_slot',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Khung giờ'),
        ),
        migrations.CreateModel(
            name='BookingNoRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255, null=True, verbose_name='Khách hàng')),
                ('date', models.DateField(null=True, verbose_name='Ngày đặt')),
                ('note', models.TextField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số ĐT')),
                ('isCompleted', models.BooleanField(default=False, verbose_name='Đã xử lí')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.service', verbose_name='Dịch vụ')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.timeslot', verbose_name='Khung giờ')),
            ],
            options={
                'verbose_name_plural': 'Lịch hẹn (khách vãng lai)',
            },
        ),
    ]
