# Generated by Django 3.2.15 on 2022-09-09 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0012_auto_20220908_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.service', verbose_name='Dịch vụ sửa chữa'),
        ),
    ]
